package com.example.orientus.enums;

public enum ApplicationStep {
    APPLICATION_RECEIVED,
    STUDENT_CONTACTED,
    DOSSIER_IN_PREPARATION,
    DOSSIER_READY,
    UNIVERSITY_CONTACTED,
    UNIVERSITY_ACCEPTED,
    UNIVERSITY_REJECTED,
    VISA_PROCESSING,
    VISA_ACCEPTED,
    VISA_REJECTED
}
